buildVariable: true
familyName: Noto Sans Canadian Aboriginal
googleFonts: true
includeSubsets:
- from: Noto Sans
  name: GF_Latin_Core
- from: Noto Sans
  ranges:
  - end: 9676
    start: 9676
recipeProvider: noto
sources:
- NotoSansCanadianAboriginal.glyphspackage
